services:
    # Query Engine
    query-engine:
        build:
            args:
                user: query-engine-user
                uid: 1000
            context: .
        image: query-engine-image
        deploy:
            replicas: 2 # 2 services for load balancing
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - query-engine-network
    # NGINX
    webserver:
        image: nginx:alpine
        container_name: webserver_container
        ports:
            - 80:80
        depends_on:
            - query-engine
        volumes:
            - ./:/var/www
            - ./deployment/nginx/:/etc/nginx/conf.d
        networks:
            - query-engine-network
networks:
    query-engine-network:
        driver: bridge
