services:
    laravel:
        build: .
        image: query-engine-image
        working_dir: /var/www
        volumes:
            - ./public:/var/www/public # Bind mount to host's ./public directory
            - /var/www/vendor
            - /var/www/node_modules
            # - /var/www/public
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - app

    caddy:
        image: caddy:2
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./public:/srv # Mount public directory to Caddy's web root
            - caddy_data:/data # This is important for persisting certificates
            - caddy_config:/config
        depends_on:
            - laravel
        networks:
            - app

volumes:
    caddy_data:
    caddy_config:

networks:
    app:
        driver: bridge
