services:
    laravel:
        build: .
        image: query-engine-image
        working_dir: /var/www
        volumes:
            - ./public:/var/www/public
            - /var/www/vendor
            - /var/www/node_modules
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - REDIS_HOST=redis
        networks:
            - app

    caddy:
        image: caddy:2
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./public:/srv
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - laravel
        networks:
            - app

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - app

volumes:
    caddy_data:
    caddy_config:
    redis_data:

networks:
    app:
        driver: bridge
