services:
    # Query Engine
    query-engine:
        build:
            args:
                user: query-engine-user
                uid: 1000
            context: .
        image: query-engine-image
        deploy:
            replicas: 2
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - query-engine-network

    # Caddy
    caddy:
        image: caddy:2
        container_name: caddy_container
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
            - ./caddy_config:/config
        depends_on:
            - query-engine
        networks:
            - query-engine-network

networks:
    query-engine-network:
        driver: bridge
