name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      registry:
        description: 'The Docker registry URL'
        required: true
        type: string
      image_name:
        description: 'The Docker image name'
        required: true
        type: string

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        service: [spider, indexer]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ inputs.registry }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: |
          docker build -t ${{ inputs.registry }}/$(echo "${{ inputs.image_name }}" | tr '[:upper:]' '[:lower:]')/${{ matrix.service }}:latest .

      - name: Push Docker image for ${{ matrix.service }}
        run: docker push ${{ inputs.registry }}/$(echo "${{ inputs.image_name }}" | tr '[:upper:]' '[:lower:]')/${{ matrix.service }}:latest
