name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tests:
    uses: ./.github/workflows/unit-test.yml
  # Add building of the rust tool

  build-and-push-docker-images:
    uses: ./.github/workflows/build-docker-images.yml
    with:
      registry: ${{ env.REGISTRY }}
    # needs: [test-spider, test-indexer]

  upload-docker-compose-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [spider, indexer]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload ${{ matrix.service }} docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-docker-compose
          path: ./services/${{ matrix.service }}/docker-compose.yml

  testing-this-thing:
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: |
        ls
        echo "Hello"
  #       run: |
  #         mkdir -p artifacts
  #         mkdir -p artifacts/spider
  #         mkdir -p artifacts/indexer
  #         ls
  #     - name: Download spider artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: spider-docker-compose
  #         path: artifacts/spider
  #     - name: Download indexer artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: indexer-docker-compose
  #         path: artifacts/indexer
  #     - name: Debug directories
  #       run: ls
  #     - name: Prepare server directories
  #       uses: appleboy/ssh-action@v1.2.2
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key:  ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: ${{ secrets.SSH_PORT }}
  #         script: |
  #           pwd
  #           ls -R
  #           mkdir -p ~/SearchEngine/Spider
  #           mkdir -p ~/SearchEngine/Indexer
  #           mkdir -p ~/SearchEngine/Monitoring
  #           ls -R
  #     - name: Copy artifacts to server
  #       uses: appleboy/scp-action@v0.1.7
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key:  ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: ${{ secrets.SSH_PORT }}
  #         source: "artifacts"
  #         target: ~/SearchEngine
