name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Unit Testing
    uses: ./.github/workflows/unit-test.yml
  # Add building of the rust tool

  build-and-push-docker-images:
    name: Build Docker Images
    needs: [tests]
    uses: ./.github/workflows/build-docker-images.yml
    with:
      registry: 'ghcr.io'
      image_name: ${{ github.repository }}

  upload-docker-compose-artifacts:
    name: Upload Docker Compose Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [spider, indexer]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload ${{ matrix.service }} docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-docker-compose
          path: ./services/${{ matrix.service }}/docker-compose.yml

  deploy:
    needs: [upload-docker-compose-artifacts]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare deployment folder
      run: |
        mkdir -p artifacts
        mkdir -p artifacts/spider
        mkdir -p artifacts/indexer
        ls
    - name: Download spider docker artifact
      uses: actions/download-artifact@v4
      with:
        name: spider-docker-compose
        path: artifacts/spider
    - name: Download indexer docker artifact
      uses: actions/download-artifact@v4
      with:
        name: indexer-docker-compose
        path: artifacts/indexer
    - name: Debug contents
      run: ls artifacts -R
    - name: Copy artifacts to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "artifacts/*" # Only copy the contents, not the folder
        target: ~/SearchEngine
    - name: Fix directories and reboot server dependencies
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key:  ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          mkdir -p ~/SearchEngine/Spider
          mkdir -p ~/SearchEngine/Indexer
          mkdir -p ~/SearchEngine/Monitoring
          cd ~/SearchEngine
          pwd
          mv spider/docker-compose.yml ./Spider/
          mv indexer/docker-compose.yml ./Indexer/
          rm spider indexer -r
          ls -R
          cd Spider
          docker compose down
          docker compose up --build -d
          cd ..
          cd Indexer
          docker compose down
          docker compose up --build -d
