name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-spider:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
    - name: Build
      working-directory: ./services/spider
      run: go build -v ./cmd/spider/main.go
    - name: Test
      working-directory: ./services/spider
      run: go test -v ./...
  # Add unit-test for the other services once I have them
  test-indexer:
    runs-on: ubuntu-latest
    steps:
    - name: Indexer Placeholder
      run: echo "Indexer Placeholder!"

  build-and-push-docker-images:
    # needs: [test-spider, test-indexer]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        service: [spider, indexer]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # - name: Debug metadata for ${{ matrix.service }}
      #   run: |
      #     echo "Tags: ${{ steps.meta.outputs.tags }}"
      #     echo "Labels: ${{ steps.meta.outputs.labels }}"
      #
      # - name: Debug tag for ${{ matrix.service }}
      #   run : |
      #     echo "Tag: ${{ env.REGISTRY }}/$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')/${{ matrix.service }}:latest"
      - name: Build Docker image for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
          # docker build -t ${{ env.REGISTRY }}/$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')/${{ matrix.service }}:latest .
        run: |
          docker build -t ${{ steps.meta.outputs.tags }} .

      - name: Push Docker image for ${{ matrix.service }}
          # docker push ${{ env.REGISTRY }}/$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')/${{ matrix.service }}:latest
        run: |
          docker push ${{ steps.meta.outputs.tags }}



