name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-spider:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
    - name: Build
      working-directory: ./services/spider
      run: go build -v ./cmd/spider/main.go
    - name: Test
      working-directory: ./services/spider
      run: go test -v ./...
  # Add unit-test for the other services once I have them
  test-indexer:
    runs-on: ubuntu-latest
    steps:
    - name: Indexer Placeholder
      run: echo "Indexer Placeholder!"
build-and-push-docker-images:
    needs: [test-spider, test-indexer]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: |
          for service in spider indexer; do
            IMAGE_NAME=${{ env.REGISTRY }}/$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')-$service
            docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$sha_short ./services/$service
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$sha_short
          done
