name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      working-directory: ./services/spider
      run: go build -v ./cmd/spider/main.go
    - name: Test
      working-directory: ./services/spider
      run: go test -v ./...
  # Add other services once I have tests for them

